version: '3.8'
services:
  mongodb:
    image: mongo:6.0.6
    container_name: random-data-ingestion-mongodb
    restart: unless-stopped
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb/db:/data/db
  postgres:
      image: postgres:14.1-alpine
      container_name: random-data-ingestion-postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./data/postgres/db:/var/lib/postgresql/data

